#!/usr/bin/env bash

## Description: Initialize stack and site
## Usage: init
## Example: "ddev init"

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- Execution --------------------------------

# Stack initialization
echo -e "${green_bg} Step 1 ${NC}${green} Initializing stack...${NC}"
ddev start

# Site initialization
echo -e "${green_bg} Step 2 ${NC}${green} Initializing site...${NC}"

# Import latest DB dump
cd "$DDEV_APPROOT"
# shellcheck disable=SC2012
OUTPUT="$(ls -t -- *.sql | head -n1)"
echo -e "Newest DB dump: ${yellow}${OUTPUT}${NC}"
ddev import-db --file="$OUTPUT"

ddev init-site

echo -en "${green_bg} DONE! ${NC} "
echo -e "Open ${yellow}https://aggro.ddev.site${NC} in your browser to verify the setup."

#-------------------------- END: Execution --------------------------------
