name: 'Setup PHP Environment'
description: 'Sets up PHP with extensions and Composer'

inputs:
  php-version:
    description: 'PHP version to set up'
    required: true
    default: '8.2'
  extensions:
    description: 'PHP extensions to install'
    required: false
    default: 'mbstring, intl, json, xml'
  coverage:
    description: 'Code coverage tool to install'
    required: false
    default: 'none'
  tools:
    description: 'Composer tools to install'
    required: false
    default: 'composer'

runs:
  using: 'composite'
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.extensions }}
        coverage: ${{ inputs.coverage }}
        tools: ${{ inputs.tools }}

    - name: Get Composer cache directory
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-