#!/usr/bin/env bash

## Run application tasks
## Usage: fin admin

cd "$PROJECT_ROOT" || exit

echo -e "\\n\\033[1;33mUpdating news...\\033[0m"
fin fire aggro news

echo -e "\\n\\033[1;33mUpdating Vimeo...\\033[0m"
fin fire aggro vimeo

echo -e "\\n\\033[1;33mUpdating YouTube...\\033[0m"
fin fire aggro youtube

echo -e "\\n\\033[1;33mCleaning up...\\033[0m"
fin fire aggro sweep

echo -e "\\n\\033[1;33mTweet (test)...\\033[0m"
fin fire aggro twitter

echo -e "\\n\\033[1;33mShow aggro log...\\033[0m"
fin fire aggro log

echo -e "\\n\\033[1;33mShow error log...\\033[0m"
fin fire aggro log-error

echo -e "\\n\\033[1;33mClearing aggro logs...\\033[0m"
fin fire aggro log-clean

echo -e "\\n\\033[1;33mClearing error logs...\\033[0m"
fin fire aggro log-error-clean

echo -e "\\n\\033[1;33mClearing news cache...\\033[0m"
fin fire aggro news-cache

echo -e "\\n\\033[1;33mClearing news stories...\\033[0m"
fin fire aggro news-clean
