#!/usr/bin/env bash

## Deploy to development server
## Usage: fin deploy-dev

cd "$PROJECT_ROOT" || exit

echo -e "\\n\\033[1;33mDeploying to development server...\\033[0m"
fin exec vendor/bin/deployer.phar deploy stage=dev
