#!/usr/bin/env bash

## Install composer and node dependencies
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- Execution --------------------------------


cd "$PROJECT_ROOT"
# shellcheck disable=SC2012
OUTPUT="$(ls -t -- *.sql | head -n1)"
echo -e "Newest DB dump: ${yellow}${OUTPUT}${NC}"

fin db import "$OUTPUT"

# install dependencies
fin composer install
fin exec npm install

# add Drupal PHPCS sniffs
fin exec phpcs --config-set installed_paths /var/www/vendor/drupal/coder/coder_sniffer

#-------------------------- END: Execution --------------------------------
