#!/usr/bin/env bash

#: exec_target = cli

## Install composer and node dependencies
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- Execution --------------------------------

# Node stuff
# -------------------------------------------

# shellcheck source=/dev/null
source ~/.bashrc
# shellcheck source=/dev/null
source ~/.nvm/nvm.sh
nvm install --lts
nvm use --lts

# Print Node version and location
which node

# Install NPM dependencies
npm install

# Install dependencies
composer install

# Add Drupal PHPCS sniffs
phpcs --config-set installed_paths /var/www/vendor/drupal/coder/coder_sniffer

# Adjust permissions
if [ -f "/var/www/.ssh/aggro" ]; then
  chmod 600 /var/www/.ssh/aggro*
else
  echo -e "\\n${yellow}No SSH keys found${NC}"
fi;

if ! [ -f "/var/www/.env" ]; then
  echo -e "\\n${yellow}Using .env-sample${NC}"
  cp .env-sample .env
fi;

#-------------------------- END: Execution --------------------------------
