#!/usr/bin/env bash

## Run specific PHPCS
## Usage: fin sniff

# Abort if anything fails
set -e

cd "$PROJECT_ROOT"
fin exec phpcs app/Controllers app/Models app/Views --report=summary --standard='Drupal,DrupalPractice'
