#!/usr/bin/env bash

## Run specific PHPCS
## Usage: fin sniff

# Abort if anything fails
set -e

display_report=''
if [ "$1" == "report" ]; then
    display_report='--report=summary'
fi

cd "$PROJECT_ROOT"
fin exec phpcs app/Controllers app/Models app/Views --ignore=*/_ci3/*,*/Views/errors/* ${display_report} --standard='Drupal,DrupalPractice' -s --exclude=DrupalPractice.CodeAnalysis.VariableAnalysis
