#!/usr/bin/env bash

## Usage: fin ssl-cert

# Abort if anything fails
set -e

# Console colors
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'

cd "$HOME/.docksal"
if [ ! -d "certs" ]
  then
  echo "Creating certs directory..."
  mkdir certs
  fin system reset
fi

if test ! "$(brew --version)"
  then
  echo "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
else
  echo "Updating installed Homebrew..."
  brew update
  brew upgrade
fi

echo "Brew install mkcert..."
brew install mkcert

# for Firefox
echo "Brew install nss..."
brew install nss
mkcert -install

cd "${PROJECT_ROOT}/${DOCROOT}"

echo "Install fin mkcert addon..."
fin addon install mkcert -g

echo "Creating cert..."
fin mkcert create
fin project restart

echo -e "${green}Self-signed cert created. Visit${NC} ${yellow}https://${VIRTUAL_HOST}${NC} ${green}in a browser to confirm.${NC}"

echo -e "${red}Note: the browser may warn that the certificate is not from a trusted certificate authority. Accept the warning to use the self-signed certificate locally.${NC}"
