#!/usr/bin/env bash

## Description: Check response code from local URLs
## Usage: check
## Example: "ddev check"

# Abort if anything fails
set -e

echo -e "\\n\\033[1;33mChecking local URL responses for errors...\\033[0m"

curl -o /dev/null -s -f -w "%{http_code}" "$DDEV_PRIMARY_URL" | grep -q "^200$" || { echo "Error on $DDEV_PRIMARY_URL: Response code is not 200"; exit 1; }

curl -o /dev/null -s -f -w "%{http_code}" "$DDEV_PRIMARY_URL/stream" | grep -q "^200$" || { echo "Error on $DDEV_PRIMARY_URL/stream: Response code is not 200"; exit 1; }

curl -o /dev/null -s -f -w "%{http_code}" "$DDEV_PRIMARY_URL/video" | grep -q "^200$" || { echo "Error on $DDEV_PRIMARY_URL/video: Response code is not 200"; exit 1; }

echo -e "\\n\\033[1;33mAll URLs returned 200...\\033[0m"
