#!/usr/bin/env bash

## Description: Run controller from CLI
## Usage: fire
## Example: "ddev fire aggro log"

# Abort if anything fails
set -e

if [ "$1" ] && [ "$2" ];
  then
    php /var/www/html/public/index.php "$1" "$2"
  else
    echo -e "\\n\\033[1;33mSpecify a controller and method.\\033[0m"
    echo -e "\\033[1;33mDo you need one of these?\\033[0m"
    echo -e "aggro log"
    echo -e "aggro log-error"
    echo -e "aggro log-clean"
    echo -e "aggro log-error-clean"
    echo -e "aggro news-clean"
    echo -e "aggro news-cache"
    echo -e "aggro vimeo/VIDEO_ID"
    echo -e "aggro youtube/VIDEO_ID"
    echo -e "aggro news"
    echo -e "aggro sweep"
fi;
