#!/usr/bin/env bash

## Description: Install composer and node dependencies
## Usage: init-site
## Example: "ddev init-site"

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- Execution --------------------------------

# Print Node version and location
which node

# Install NPM dependencies
npm install

# Install dependencies
composer install

if ! [ -f "/var/www/html/.env" ]; then
  echo -e "\\n${yellow}Using .env-sample${NC}"
  cp .env-sample .env
fi;

#-------------------------- END: Execution --------------------------------
