#!/usr/bin/env bash

## Description: Run shellcheck on custom commands
## Usage: shellcheck
## Example: "ddev shellcheck"

# Abort if anything fails
set -e

if ! command -v shellcheck > /dev/null 2>&1; then
  echo -e "\\n\\033[1;33mInstalling ShellCheck...\\033[0m"
  sudo DEBIAN_FRONTEND=noninteractive apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq shellcheck
  echo -e "\\nShellCheck installed."
fi

echo -e "\\n\\033[1;33mRunning ShellCheck on DDEV commands...\\033[0m"
# Exclude non-shell files (README.txt, .gitattributes)
find .ddev/commands/host .ddev/commands/web -type f ! -name '*.txt' ! -name '.git*' -print0 | xargs -0 shellcheck
echo -e "\\nNo issues!"
