name: Test macOS build

on:
  workflow_dispatch: # enable run button on github.com
  push:
    branches:
      - "macos-action"
  schedule:
    - cron: "0 2 7,21 * *" # At 02:00 on day-of-month 7 and 21.

jobs:
  install-docksal:
    name: Build docksal project on macOS
    runs-on: macos-12
    steps:
      - name: Install Docker Desktop
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
          brew install socat
          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
          open -a /Applications/Docker.app --args --unattended --accept-license
          echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
      - name: Run docksal installer
        run: curl -fsSL https://get.docksal.io | bash
      - name: Display docksal system info
        run: fin sysinfo
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Init docksal project
        run: |
          fin init
          fin sniff
          fin shellcheck
          fin admin
      - name: Run Accessibility Insights site-wide
        uses: microsoft/accessibility-insights-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          max-urls: 1
          url: http://aggro.docksal.site
          input-urls: http://aggro.docksal.site/sites http://aggro.docksal.site/sites/bmxfeed http://aggro.docksal.site/stream http://aggro.docksal.site/submit http://aggro.docksal.site/about http://aggro.docksal.site/video
      - name: Upload Accessibility Insights report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: accessibility-reports
          path: ${{ github.workspace }}/_accessibility-reports
