name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  front:
    name: Lint CSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'
          cache: 'npm'
      - name: Process and lint
        run: |
          npm install
          npm run test
  back:
    name: Lint PHP
    runs-on: ubuntu-latest
    needs: front
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: composer
      - name: Composer install and lint
        run: |
          composer install
          composer lint
